apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-green
  labels:
    app: java-app
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-app
      version: green
  template:
    metadata:
      labels:
        app: java-app
        version: green
    spec:
      containers:
        - name: java-app
          image: your-registry/java-spring-devops:1.0
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: "green-1.0"