apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  selector:
    app: java-app
    version: blue  # This switches between blue/green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080